theme: minima
title: Edward's Deep Learning Journey
description: Hi internet stranger! I intend for this to be a website for myself to track my progress self studying deep learning. Feel free to peruse for interesting thoughts or links to resources to self-study DL topics.
