title: Edward's Deep Learning Journey
description: A website to track my progress (or lack thereof) self-studying deep learning. 
author: "Edward Yao"

theme: minima

markdown: kramdown

base_url: /gh-pages-minima-starter

# Minima social links
github_username: edwardcdy
linkedin_username: edwardcdy

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/jobs.md
  - _pages/archive.md
  - _pages/resources.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
